export const estadosRepublica = [
  {
    nombre: "Aguascalientes",
    abreviacion: "AG",
    ciudades: [
      "Aguascalientes",
      "Jesús María",
      "Calvillo",
      "Rincón de Romos",
      "Pabellón de Arteaga",
    ],
  },
  {
    nombre: "Baja California",
    abreviacion: "BC",
    ciudades: [
      "Tijuana",
      "Mexicali",
      "Ensenada",
      "Tecate",
      "Playas de Rosarito",
      "San Felipe",
    ],
  },
  {
    nombre: "Baja California Sur",
    abreviacion: "BS",
    ciudades: [
      "La Paz",
      "Los Cabos",
      "Comondú",
      "Loreto",
      "Mulegé",
    ],
  },
  {
    nombre: "Campeche",
    abreviacion: "CC",
    ciudades: [
      "Campeche",
      "Ciudad del Carmen",
      "Escárcega",
      "Champotón",
      "Calkiní",
    ],
  },
  {
    nombre: "Chiapas",
    abreviacion: "CS",
    ciudades: [
      "Tuxtla Gutiérrez",
      "San Cristóbal de las Casas",
      "Tapachula",
      "Comitán de Domínguez",
      "Palenque",
      "Ocosingo",
    ],
  },
  {
    nombre: "Chihuahua",
    abreviacion: "CH",
    ciudades: [
      "Chihuahua",
      "Ciudad Juárez",
      "Delicias",
      "Cuauhtémoc",
      "Parral",
      "Nuevo Casas Grandes",
    ],
  },
  {
    nombre: "Ciudad de México",
    abreviacion: "DF",
    ciudades: [
      "Gustavo A. Madero",
      "Iztapalapa",
      "Álvaro Obregón",
      "Coyoacán",
      "Tlalpan",
      "Xochimilco",
      "Benito Juárez",
      "Cuauhtémoc",
    ],
  },
  {
    nombre: "Coahuila",
    abreviacion: "CL",
    ciudades: [
      "Saltillo",
      "Torreón",
      "Monclova",
      "Piedras Negras",
      "Acuña",
      "Sabinas",
    ],
  },
  {
    nombre: "Colima",
    abreviacion: "CM",
    ciudades: [
      "Colima",
      "Manzanillo",
      "Tecomán",
      "Villa de Álvarez",
      "Armería",
    ],
  },
  {
    nombre: "Durango",
    abreviacion: "DG",
    ciudades: [
      "Durango",
      "Gómez Palacio",
      "Lerdo",
      "Santiago Papasquiaro",
      "Guadalupe Victoria",
    ],
  },
  {
    nombre: "Estado de México",
    abreviacion: "MC",
    ciudades: [
      "Toluca",
      "Ecatepec de Morelos",
      "Naucalpan de Juárez",
      "Nezahualcóyotl",
      "Tlalnepantla de Baz",
      "Texcoco",
      "Metepec",
      "Ixtapaluca",
    ],
  },
  {
    nombre: "Guanajuato",
    abreviacion: "GT",
    ciudades: [
      "Guanajuato",
      "León",
      "Irapuato",
      "Celaya",
      "Salamanca",
      "San Miguel de Allende",
    ],
  },
  {
    nombre: "Guerrero",
    abreviacion: "GR",
    ciudades: [
      "Chilpancingo de los Bravo",
      "Acapulco de Juárez",
      "Iguala de la Independencia",
      "Zihuatanejo",
      "Taxco de Alarcón",
    ],
  },
  {
    nombre: "Hidalgo",
    abreviacion: "HG",
    ciudades: [
      "Pachuca de Soto",
      "Tulancingo",
      "Tula de Allende",
      "Actopan",
      "Huejutla de Reyes",
    ],
  },
  {
    nombre: "Jalisco",
    abreviacion: "JC",
    ciudades: [
      "Guadalajara",
      "Zapopan",
      "Tlaquepaque",
      "Tonalá",
      "Puerto Vallarta",
      "Lagos de Moreno",
      "Tepatitlán de Morelos",
    ],
  },
  {
    nombre: "Michoacán",
    abreviacion: "MN",
    ciudades: [
      "Morelia",
      "Uruapan",
      "Zamora",
      "Lázaro Cárdenas",
      "Pátzcuaro",
      "Apatzingán",
    ],
  },
  {
    nombre: "Morelos",
    abreviacion: "MS",
    ciudades: [
      "Cuernavaca",
      "Jiutepec",
      "Temixco",
      "Cuautla",
      "Yautepec",
      "Emiliano Zapata",
    ],
  },
  {
    nombre: "Nayarit",
    abreviacion: "NT",
    ciudades: [
      "Tepic",
      "Bahía de Banderas",
      "Santiago Ixcuintla",
      "Compostela",
      "Acaponeta",
    ],
  },
  {
    nombre: "Nuevo León",
    abreviacion: "NL",
    ciudades: [
      "Monterrey",
      "Guadalupe",
      "San Nicolás de los Garza",
      "Apodaca",
      "General Escobedo",
      "Santa Catarina",
      "San Pedro Garza García",
      "Linares",
    ],
  },
  {
    nombre: "Oaxaca",
    abreviacion: "OC",
    ciudades: [
      "Oaxaca de Juárez",
      "Salina Cruz",
      "San Juan Bautista Tuxtepec",
      "Juchitán de Zaragoza",
      "Huajuapan de León",
    ],
  },
  {
    nombre: "Puebla",
    abreviacion: "PL",
    ciudades: [
      "Puebla de Zaragoza",
      "Tehuacán",
      "San Martín Texmelucan",
      "Atlixco",
      "Cholula",
      "Huauchinango",
    ],
  },
  {
    nombre: "Querétaro",
    abreviacion: "QT",
    ciudades: [
      "Santiago de Querétaro",
      "San Juan del Río",
      "El Marqués",
      "Corregidora",
      "Tequisquiapan",
    ],
  },
  {
    nombre: "Quintana Roo",
    abreviacion: "QR",
    ciudades: [
      "Cancún",
      "Chetumal",
      "Playa del Carmen",
      "Cozumel",
      "Tulum",
      "Felipe Carrillo Puerto",
    ],
  },
  {
    nombre: "San Luis Potosí",
    abreviacion: "SP",
    ciudades: [
      "San Luis Potosí",
      "Soledad de Graciano Sánchez",
      "Matehuala",
      "Ciudad Valles",
      "Rioverde",
    ],
  },
  {
    nombre: "Sinaloa",
    abreviacion: "SL",
    ciudades: [
      "Culiacán",
      "Mazatlán",
      "Los Mochis",
      "Guasave",
      "Guamúchil",
      "Navolato",
    ],
  },
  {
    nombre: "Sonora",
    abreviacion: "SR",
    ciudades: [
      "Hermosillo",
      "Ciudad Obregón",
      "Nogales",
      "San Luis Río Colorado",
      "Navojoa",
      "Guaymas",
    ],
  },
  {
    nombre: "Tabasco",
    abreviacion: "TC",
    ciudades: [
      "Villahermosa",
      "Cárdenas",
      "Comalcalco",
      "Macuspana",
      "Huimanguillo",
    ],
  },
  {
    nombre: "Tamaulipas",
    abreviacion: "TS",
    ciudades: [
      "Ciudad Victoria",
      "Reynosa",
      "Matamoros",
      "Nuevo Laredo",
      "Tampico",
      "Altamira",
    ],
  },
  {
    nombre: "Tlaxcala",
    abreviacion: "TL",
    ciudades: [
      "Tlaxcala de Xicohténcatl",
      "Apizaco",
      "Huamantla",
      "Calpulalpan",
      "Santa Ana Chiautempan",
    ],
  },
  {
    nombre: "Veracruz",
    abreviacion: "VZ",
    ciudades: [
      "Veracruz",
      "Xalapa",
      "Coatzacoalcos",
      "Córdoba",
      "Orizaba",
      "Poza Rica",
      "Tuxpan",
    ],
  },
  {
    nombre: "Yucatán",
    abreviacion: "YN",
    ciudades: [
      "Mérida",
      "Kanasín",
      "Umán",
      "Valladolid",
      "Progreso",
      "Tizimín",
    ],
  },
  {
    nombre: "Zacatecas",
    abreviacion: "ZS",
    ciudades: [
      "Zacatecas",
      "Fresnillo",
      "Guadalupe",
      "Jerez de García Salinas",
      "Río Grande",
    ],
  },
];
